### ISSUE TITLE
Please make a hackage release

### ISSUE THREAD

**Issue by maksbotan** [Palmik/bson-generic#9]
Hi!

This library compiles and works well on LTS-11.14 (with ghc-8.2) when using version from Github. However, last release on Hackage does not compile, since it does not have latest commits with cabal file updates.

Could you please make a new Hackage release with the state of current master? We are using `bson-generic` at @biocad and we'd like to see it on Hackage.

**Comment by Palmik** [comment]
Sorry, fixed.
